### ISSUE TITLE
azuread_sign_in_report fails with  Error: null (SQLSTATE HV000)

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azuread#150]
**Describe the bug**

Below results null, where 
```sql
> select * from azuread_sign_in_report limit 10

Error: null (SQLSTATE HV000)

```

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by ehazboun-Reply** [comment]
running into the same issue here. Granted the right permissions to the user, yet still receiving

Error: null (SQLSTATE HV000)

as result to any query for azuread resources.

**Comment by ParthaI** [comment]
@ehazboun-Reply, Thanks for sharing your experience 

We would appreciate it if you could let us know the following.

- Do you get this error only for the `azuread_sign_in_report ` table, or do you see the error across all the tables?
- Which authentication mode are you using, such as AzureCLI Based authentication, client secret authentication, or anything else as per mentioned in [doc](https://github.com/turbot/steampipe-plugin-azuread/blob/main/config/azuread.spc)?
- In our case, we tested the above scenarios with client secret authentication, which had a smooth execution. Could you please give it a try?
- It would be helpful if you could test the `update-msgraph-sdk-version` branch from the [PR](https://github.com/turbot/steampipe-plugin-azuread/pull/152) and share any errors that occur.
- If you encounter the error `Error: {"Code":"","Message":"Unknown AppliedConditionalAccessPolicyResult value: reportOnlyNotApplied"}` while querying this table, it indicates that the user lacks the necessary permissions for making the API call.
- The user needs to be granted specific [permissions](https://learn.microsoft.com/en-gb/graph/api/signin-list?view=graph-rest-1.0&tabs=http#permissions) for quering the table `azuread_sign_in_report`, including roles like **Global Administrator**, **Global Reader**, **Reports Reader**, **Security Administrator**, **Security Operator**, and **Security Reader**.

Steps for testing out the PR branch `update-msgraph-sdk-version`:

- git clone https://github.com/turbot/steampipe-plugin-azuread.git
- cd steampipe-plugin-azuread
- git checkout `update-msgraph-sdk-version`
- make
- Run steampipe query

Thank You!

**Comment by ehazboun-Reply** [comment]
Hi @ParthaI, thanks for the quick response. Here are my answers:

- I get the errors for all tables or queries with azuread
- I used AzureCLI authentication (both device code and normal way)
- I cannot use client authentication on the particular tenant, I am working on. If I have some time, I will try with another tenant and client credentials.
- I have tested the branch mentioned. You can see my comment about the results here: https://github.com/turbot/steampipe-plugin-azuread/pull/152#issuecomment-1825516158
- The user has Global Reader & Security Reader on directory level

Thank you!

**Comment by ParthaI** [comment]
Hello @ehazboun-Reply, Thanks for testing the branch and sharing your observations.

Per the [comment](https://github.com/turbot/steampipe-plugin-azuread/pull/152#issuecomment-1825516158), I have a few findings regarding the error:

```
Error: {"Code":"","Message":"received a claim for CAE but azure identity doesn't support claims: {\"access_token\":{\"nbf\":{\"essential\":true,\"value\":\"1700823904\"},\"xms_rp_ipaddr\":{\"value\":\"REDACTED\"}}}
```

- I've made another attempt to replicate the error with the authentication module you're using, but unfortunately, I haven't had any success with it (I tried both with Steampipe and Azure CLI).

- Since we're utilizing `AzureCLI Based Authentication` for querying the tables, and the plugin does support AzureCLI Based Authentication, we should expect to retrieve the data. 
  - Would you please consider running the equivalent Azure CLI command to retrieve details for the table you're querying? Additionally, if possible, could you share the credential file `~/.steampipe/config/azuread.spc` (with sensitive information removed, of course)?

- The error message suggests that the claim for Continuous Access Evaluation (CAE) isn't supported by the SDK version we're currently using.
  - It's possible that there are [Conditional Access Policies](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-policy-common?tabs=secure-foundation) configured in the tenant and applied to the user or group you're using to access the results. These policies might be refreshing the authentication token based on the conditions specified in the policy.
  - The Azure SDK attempts to claim the refresh token but encounters an issue because the CAE claim functionality isn't supported in our current SDK version.
  - The Go packages `azidentity` (github.com/Azure/azure-sdk-for-go/sdk/azidentity) and `azcore` (github.com/Azure/azure-sdk-for-go/sdk/azcore) are responsible for supporting this functionality.
  - I've identified an issue raised in the Azure Go SDK repository at https://github.com/Azure/azure-sdk-for-go/issues/14931, which appears to be related to the error you're encountering.
  - In our setup, we're using `azidentity` package version `v1.1.0`, which does support this feature. However, packages `azidentity v1.3.0-beta.3` and `azcore v1.4.0-beta.1` have made changes, and credentials now default to sending CP1 and ARM clients internally to handle claims challenges.
  - CHANGELOG for [azcore](https://github.com/Azure/azure-sdk-for-go/blob/9858c485b320dd70ac8464bf83820baea133efbb/sdk/azcore/CHANGELOG.md#180-2023-10-05) and [azidentity](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/CHANGELOG.md#140-2023-10-10) packages.

- I've pushed the changes by upgrading the package version of `azidentity` in the same branch. Could you please give it a try and let us know if you encounter any further issues?

- Unfortunately, I haven't been able to test by applying any Conditional Access policies in our tenant for our test environment. This is because other users on our team may also be affected by this policy, as we're using the same credentials for testing the plugins.

Appriciated your cooperation with us. Thank you!

**Comment by ehazboun-Reply** [comment]
hello @ParthaI,

I couldn't find the time today to investigate the topic further. But I have some good news. After using the latest changes you've made. The queries now work and the data is being retrieved correctly from Entra ID.

So the issue was indeed due to CAE. Thanks a lot!

I will be further testing the plugin on this branch and let you know, if I encounter other issues.
