### ISSUE TITLE
Remove restriction of 999 results in tables and update use of top query param

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-azuread#49]
**Describe the bug**
Several tables use the `top` query param and set it to 999; this limits the number of results for those tables consistently to return max 999 rows.

**Steampipe version (`steampipe -v`)**
v0.13.5

**Plugin version (`steampipe plugin list`)**
v0.3.0

**To reproduce**
Query the table `azuread_sign_in_report` when there are more than 999 results, and only 999 will be returned.

**Expected behavior**
Tables should return all results, even if they exceed 999.

**Additional context**

**Comment by cbruno10** [comment]
This restriction should not be in place, and instead the `top` query param should be used when a limit is passed through the query in order to get the exact number of results from the Graph API.

The Hamilton SDK we're using handles paging internally and determines if paging should be enabled or not based on the `top` query param, e.g., for the [UsersClient List function](https://github.com/manicminer/hamilton/blob/main/msgraph/users.go#L28)
```
func (c *UsersClient) List(ctx context.Context, query odata.Query) (*[]User, int, error) {
	resp, status, _, err := c.BaseClient.Get(ctx, GetHttpRequestInput{
		DisablePaging:    query.Top > 0,
		OData:            query,
		ValidStatusCodes: []int{http.StatusOK},
		Uri: Uri{
			Entity:      "/users",
			HasTenantId: true,
		},
	})
	...
}
```

The `top` query param cannot be higher than 999, so if a query uses a limit more than 999, the `top` query param will not be used.
